### ISSUE TITLE
新テーマでセルフ埋め込みが埋め込みではなく記事になる

### ISSUE THREAD

**Issue by sasigume** [mlmlff/manoikura#2]
`manoikura-sage10`で発生。

```
GET https://canary.discord.com/assets/5a61f8e3e63b7e93777f.js net::ERR_ABORTED 403
5a61f8e3e63b7e93777f.js:1          Failed to load resource: the server responded with a status of 403 ()
5a61f8e3e63b7e93777f.js:1          Failed to load resource: the server responded with a status of 403 ()
widget?id=756496112126263318&theme=dark:13          GET https://canary.discord.com/assets/5a61f8e3e63b7e93777f.js net::ERR_ABORTED 403
5a61f8e3e63b7e93777f.js:1          Failed to load resource: the server responded with a status of 403 ()
5a61f8e3e63b7e93777f.js:1          Failed to load resource: the server responded with a status of 403 ()
jquery-migrate.js?ver=3.3.2:69 JQMIGRATE: Migrate is installed with logging active, version 3.3.2
jquery-migrate.js?ver=3.3.2:69 JQMIGRATE: Migrate is installed with logging active, version 3.3.2
widget:4          GET https://canary.discord.com/assets/index.f7afda7848e99e6cf0ab.css net::ERR_ABORTED 403
index.f7afda7848e99e6cf0ab.css:1          Failed to load resource: the server responded with a status of 403 ()
widget?id=756496112126263318&theme=dark:13          GET https://canary.discord.com/assets/5a61f8e3e63b7e93777f.js net::ERR_ABORTED 403
5a61f8e3e63b7e93777f.js:1          Failed to load resource: the server responded with a status of 403 ()
jquery-migrate.js?ver=3.3.2:69 JQMIGRATE: Migrate is installed with logging active, version 3.3.2
widget:4          GET https://canary.discord.com/assets/index.f7afda7848e99e6cf0ab.css net::ERR_ABORTED 403
widget?id=756496112126263318&theme=dark:13          GET https://canary.discord.com/assets/5a61f8e3e63b7e93777f.js net::ERR_ABORTED 403
www-embed-player.js:316 Uncaught DOMException: Failed to read the 'cookie' property from 'Document': The document is sandboxed and lacks the 'allow-same-origin' flag.
    at Pd.m.get (https://www.youtube.com/s/player/96dcbc8c/www-embed-player.vflset/www-embed-player.js:316:47)
    at Td (https://www.youtube.com/s/player/96dcbc8c/www-embed-player.vflset/www-embed-player.js:323:166)
    at qo (https://www.youtube.com/s/player/96dcbc8c/www-embed-player.vflset/www-embed-player.js:1120:19)
    at tr (https://www.youtube.com/s/player/96dcbc8c/www-embed-player.vflset/www-embed-player.js:1398:158)
    at https://www.youtube.com/s/player/96dcbc8c/www-embed-player.vflset/www-embed-player.js:1580:35
    at https://www.youtube.com/embed/FAGBC6uJxeE?feature=oembed&enablejsapi=1&origin=http://napoan.test:7:57310
m.get @ www-embed-player.js:316
Td @ www-embed-player.js:323
qo @ www-embed-player.js:1120
tr @ www-embed-player.js:1398
(anonymous) @ www-embed-player.js:1580
(anonymous) @ FAGBC6uJxeE?feature=oembed&enablejsapi=1&origin=http://napoan.test:7
base.js:290 Uncaught DOMException: Failed to read the 'cookie' property from 'Document': The document is sandboxed and lacks the 'allow-same-origin' flag.
    at aj.g.k.get (https://www.youtube.com/s/player/96dcbc8c/player_ias.vflset/ja_JP/base.js:6539:49)
    at dj (https://www.youtube.com/s/player/96dcbc8c/player_ias.vflset/ja_JP/base.js:530:176)
    at fj (https://www.youtube.com/s/player/96dcbc8c/player_ias.vflset/ja_JP/base.js:532:80)
    at Mla (https://www.youtube.com/s/player/96dcbc8c/player_ias.vflset/ja_JP/base.js:1527:358)
    at Object.g.Ju (https://www.youtube.com/s/player/96dcbc8c/player_ias.vflset/ja_JP/base.js:1743:148)
    at mu (https://www.youtube.com/s/player/96dcbc8c/player_ias.vflset/ja_JP/base.js:1488:332)
    at https://www.youtube.com/s/player/96dcbc8c/player_ias.vflset/ja_JP/base.js:1484:340
    at new ni (https://www.youtube.com/s/player/96dcbc8c/player_ias.vflset/ja_JP/base.js:468:110)
    at lu (https://www.youtube.com/s/player/96dcbc8c/player_ias.vflset/ja_JP/base.js:1484:56)
    at Object.g.S (https://www.youtube.com/s/player/96dcbc8c/player_ias.vflset/ja_JP/base.js:1807:230)
(anonymous) @ base.js:290
setTimeout (async)
Pe @ base.js:290
(anonymous) @ base.js:492
ji @ base.js:466
Promise.then (async)
fi @ base.js:465
g.ii @ base.js:464
Ai @ base.js:488
mi @ base.js:483
ni @ base.js:468
lu @ base.js:1484
g.S @ base.js:1807
g.QX.create @ base.js:9783
a.A @ www-embed-player.js:1535
us @ www-embed-player.js:1536
m.loadNewVideoConfig @ www-embed-player.js:1530
(anonymous) @ www-embed-player.js:1528
(anonymous) @ www-embed-player.js:601
setTimeout (async)
Lh @ www-embed-player.js:618
qs @ www-embed-player.js:1528
Ls @ www-embed-player.js:1570
(anonymous) @ www-embed-player.js:1579
(anonymous) @ FAGBC6uJxeE?feature=oembed&enablejsapi=1&origin=http://napoan.test:7
www-embed-player.js:254 Uncaught DOMException: Failed to read the 'cookie' property from 'Document': The document is sandboxed and lacks the 'allow-same-origin' flag.
    at Pd.m.get (https://www.youtube.com/s/player/96dcbc8c/www-embed-player.vflset/www-embed-player.js:316:47)
    at Td (https://www.youtube.com/s/player/96dcbc8c/www-embed-player.vflset/www-embed-player.js:323:166)
    at Vd (https://www.youtube.com/s/player/96dcbc8c/www-embed-player.vflset/www-embed-player.js:325:80)
    at Xj (https://www.youtube.com/s/player/96dcbc8c/www-embed-player.vflset/www-embed-player.js:746:343)
    at pj (https://www.youtube.com/s/player/96dcbc8c/www-embed-player.vflset/www-embed-player.js:1047:171)
    at hj (https://www.youtube.com/s/player/96dcbc8c/www-embed-player.vflset/www-embed-player.js:698:311)
    at https://www.youtube.com/s/player/96dcbc8c/www-embed-player.vflset/www-embed-player.js:694:332
    at new Df (https://www.youtube.com/s/player/96dcbc8c/www-embed-player.vflset/www-embed-player.js:466:109)
    at ej (https://www.youtube.com/s/player/96dcbc8c/www-embed-player.vflset/www-embed-player.js:694:56)
    at Kn (https://www.youtube.com/s/player/96dcbc8c/www-embed-player.vflset/www-embed-player.js:1074:226)
(anonymous) @ www-embed-player.js:254
setTimeout (async)
hd @ www-embed-player.js:254
(anonymous) @ www-embed-player.js:491
We @ www-embed-player.js:402
Promise.then (async)
Se @ www-embed-player.js:400
Re @ www-embed-player.js:399
Qf @ www-embed-player.js:486
Ef @ www-embed-player.js:482
Df @ www-embed-player.js:466
ej @ www-embed-player.js:694
Kn @ www-embed-player.js:1074
M @ www-embed-player.js:602
(anonymous) @ www-embed-player.js:601
setTimeout (async)
Lh @ www-embed-player.js:618
qs @ www-embed-player.js:1528
Ls @ www-embed-player.js:1570
(anonymous) @ www-embed-player.js:1579
(anonymous) @ FAGBC6uJxeE?feature=oembed&enablejsapi=1&origin=http://napoan.test:7
www-embed-player.js:254 Uncaught DOMException: Failed to read the 'cookie' property from 'Document': The document is sandboxed and lacks the 'allow-same-origin' flag.
    at Pd.m.get (https://www.youtube.com/s/player/96dcbc8c/www-embed-player.vflset/www-embed-player.js:316:47)
    at Td (https://www.youtube.com/s/player/96dcbc8c/www-embed-player.vflset/www-embed-player.js:323:166)
    at Vd (https://www.youtube.com/s/player/96dcbc8c/www-embed-player.vflset/www-embed-player.js:325:80)
    at Xj (https://www.youtube.com/s/player/96dcbc8c/www-embed-player.vflset/www-embed-player.js:746:343)
    at pj (https://www.youtube.com/s/player/96dcbc8c/www-embed-player.vflset/www-embed-player.js:1047:171)
    at hj (https://www.youtube.com/s/player/96dcbc8c/www-embed-player.vflset/www-embed-player.js:698:311)
    at https://www.youtube.com/s/player/96dcbc8c/www-embed-player.vflset/www-embed-player.js:694:332
    at new Df (https://www.youtube.com/s/player/96dcbc8c/www-embed-player.vflset/www-embed-player.js:466:109)
    at ej (https://www.youtube.com/s/player/96dcbc8c/www-embed-player.vflset/www-embed-player.js:694:56)
    at Kn (https://www.youtube.com/s/player/96dcbc8c/www-embed-player.vflset/www-embed-player.js:1074:226)
(anonymous) @ www-embed-player.js:254
setTimeout (async)
hd @ www-embed-player.js:254
(anonymous) @ www-embed-player.js:491
We @ www-embed-player.js:402
Promise.then (async)
Se @ www-embed-player.js:400
Re @ www-embed-player.js:399
Qf @ www-embed-player.js:486
Ef @ www-embed-player.js:482
Df @ www-embed-player.js:466
ej @ www-embed-player.js:694
Kn @ www-embed-player.js:1074
M @ www-embed-player.js:602
(anonymous) @ www-embed-player.js:601
load (async)
(anonymous) @ www-embed-player.js:1586
(anonymous) @ www-embed-player.js:1587
widget_embedder.js:106 [Violation] Added synchronous DOM mutation listener to a 'DOMNodeInserted' event. Consider using MutationObserver to make the page more responsive.
(anonymous) @ widget_embedder.js:106
base.js:290 Uncaught DOMException: Failed to read the 'cookie' property from 'Document': The document is sandboxed and lacks the 'allow-same-origin' flag.
    at aj.g.k.get (https://www.youtube.com/s/player/96dcbc8c/player_ias.vflset/ja_JP/base.js:6539:49)
    at dj (https://www.youtube.com/s/player/96dcbc8c/player_ias.vflset/ja_JP/base.js:530:176)
    at fj (https://www.youtube.com/s/player/96dcbc8c/player_ias.vflset/ja_JP/base.js:532:80)
    at Mla (https://www.youtube.com/s/player/96dcbc8c/player_ias.vflset/ja_JP/base.js:1527:358)
    at Object.g.Ju (https://www.youtube.com/s/player/96dcbc8c/player_ias.vflset/ja_JP/base.js:1743:148)
    at mu (https://www.youtube.com/s/player/96dcbc8c/player_ias.vflset/ja_JP/base.js:1488:332)
    at https://www.youtube.com/s/player/96dcbc8c/player_ias.vflset/ja_JP/base.js:1484:340
    at new ni (https://www.youtube.com/s/player/96dcbc8c/player_ias.vflset/ja_JP/base.js:468:110)
    at lu (https://www.youtube.com/s/player/96dcbc8c/player_ias.vflset/ja_JP/base.js:1484:56)
    at https://www.youtube.com/s/player/96dcbc8c/player_ias.vflset/ja_JP/base.js:1486:170
```

sage10自体が未完成なので、安定するまでこちらのテーマの使用は控える。

が、Tailwind3やtailwindcss/nestingとかを早く使いたいので、最悪そこだけ昔のテーマに導入するかもしれない。

**Comment by sasigume** [comment]
3a02171fa854619be1a38bdaac27f9e62d0a18d7 で新テーマを消したのでclose
